language: node_js

node_js:
- "13"

cache: npm

git:
  depth: false

env:
  - NATS_VERSION=v2.1.6

before_script:
  - wget "https://github.com/nats-io/nats-server/releases/download/$NATS_VERSION/nats-server-$NATS_VERSION-linux-amd64.zip" -O tmp.zip
  - unzip tmp.zip
  - mv nats-server-$NATS_VERSION-linux-amd64 nats-server

script:
- npm test

